# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{integrity-nabaztag}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Morrison"]
  s.date = %q{2009-10-09}
  s.description = %q{A Nabaztag notifier for integrity}
  s.email = %q{daniel@collectiveidea.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "integrity-nabaztag.gemspec",
     "lib/integrity/notifier/config.haml",
     "lib/integrity/notifier/nabaztag.rb",
     "vendor/nabaztag-ruby/.gitignore",
     "vendor/nabaztag-ruby/CHANGES",
     "vendor/nabaztag-ruby/README",
     "vendor/nabaztag-ruby/Rakefile",
     "vendor/nabaztag-ruby/bin/nabaztag-say",
     "vendor/nabaztag-ruby/lib/nabaztag.rb",
     "vendor/nabaztag-ruby/lib/nabaztag/choreography.rb",
     "vendor/nabaztag-ruby/lib/nabaztag/message.rb",
     "vendor/nabaztag-ruby/lib/nabaztag/response.rb",
     "vendor/nabaztag-ruby/sample/build.rb",
     "vendor/nabaztag-ruby/sample/demo.rb",
     "vendor/nabaztag-ruby/sample/interactive.rb",
     "vendor/nabaztag-ruby/sample/speech.rb",
     "vendor/nabaztag-ruby/setup.rb",
     "vendor/nabaztag-ruby/test/choreography_test.rb",
     "vendor/nabaztag-ruby/test/message_test.rb",
     "vendor/nabaztag-ruby/test/response_test.rb"
  ]
  s.homepage = %q{http://github.com/collectiveidea/integrity-nabaztag}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Nabaztag notifier for integrity}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
